import { Product } from "./interfaces/product"

export const PRODUCTS: Product[] = [
    {
        id: 1,
        name: "First item",
        description: "Mock description for item number one. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Veritatis fugit maiores saepe aliquid nostrum libero aut, debitis reprehenderit, mollitia quo recusandae deleniti a omnis dolore quibusdam exercitationem, doloribus temporibus minima excepturi! Distinctio, placeat quis vel reprehenderit repellendus ipsum dicta officiis quaerat voluptatibus qui repellat molestias nihil, officia, dignissimos minus facilis! Excepturi perspiciatis distinctio quos aut doloremque, similique veniam explicabo porro illum illo velit repudiandae beatae eveniet qui labore deserunt placeat dolor repellendus repellat nostrum at! Modi eligendi nesciunt blanditiis soluta mollitia deserunt veritatis placeat. Illo, voluptas sit? Doloribus nisi odio pariatur voluptas blanditiis, sit voluptatem, explicabo officia distinctio culpa numquam.",
        price: 100,
        photo: "https://yandex-images.clstorage.net/v5v2IP199/5528ad7KU3/EDW0krcB9x4OBwQB0jn9pwcHb5ZFWnnx5tClAMDkos5wLszxhgGAeKy5TW0_ULVjuWMcoIoR3MkmwgMHDPu6ZFNtod7yRexGXEUYVdo6-KUaWiyHWQB9rPyS-Q_R66nDdi-O8dwQ2X7i8Ec4VDvDEM0NMsCgMK3iMtBBERCi5DIDLO6RvC2GUzoCYw7qNdeDDl5WiXMXY6rC8skE8KCRswlJ2Pr1Gq9h1dEWY08P-jXYCDHWhgWTyTfeVVw8qMQdDiGsqYk1ugEkJmse8T_AoBloUIFWFkaY2OHbKMubj6smb9La3TqmaNDRFmZZPu0c2TkV3IU8ruYEzVxUKrvYJi8sqoKtBKM9JidLKfEC_ocNXXCgQhxjp_7N3SHbkqqGCnXR5dkhukHw4yBkaQvJPNomMOieG7bCHOhcSjqP2RE1EYeBpzuOADodeTbwMcC1B25EgnYNUqPc4P447KiArihM7N_VDrhW1NcCbUwI9yDVJS34ugeryiLlXlMklfwsFyCkvqs-nhsCGGYy9DHLlSlrQppLEmmqyvvrKtmeqosXaMrR3guYQ93FEkRZL8wS4wQ41YI5t-kE7WduCILjDiURsbyNCIEeLSFgLNcS6o0sU2inSztZpevc9ib2hYuuP3Xw3dQxlWnz6jhZQCPlJ808MvqPGpXpI_JOTzmV7y8CMpqiih2wMAMNTS_wB-qRMmRQvlwzcbfm8-wm-6eJjC56x8rgFJh31sg-a008-xnXMBThjxuTyQP-YlMLrcsTCheoho0VnR0lPE0r3i7btAdbTbl6EHaa9_LvCPuKqbsvTfnd6wabee_rHEhCEuMg9QY5yKAOkN0Ew0ZaIILiOAsyraaNCLoQOBx-CPc80LEYSFKrQCdCotjzwCjEiY-dI13ZysIniXns8DJ4eCXpP84cKce-DbbrE_dydA6oxycrGqmGqRadNzADfjzCPcGmDF17pmE2dprL5tYLxIM"
    },
    {
        id: 2,
        name: "Second item",
        description: "Mock description for item number two. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Veritatis fugit maiores saepe aliquid nostrum libero aut, debitis reprehenderit, mollitia quo recusandae deleniti a omnis dolore quibusdam exercitationem, doloribus temporibus minima excepturi! Distinctio, placeat quis vel reprehenderit repellendus ipsum dicta officiis quaerat voluptatibus qui repellat molestias nihil, officia, dignissimos minus facilis! Excepturi perspiciatis distinctio quos aut doloremque, similique veniam explicabo porro illum illo velit repudiandae beatae eveniet qui labore deserunt placeat dolor repellendus repellat nostrum at! Modi eligendi nesciunt blanditiis soluta mollitia deserunt veritatis placeat. Illo, voluptas sit? Doloribus nisi odio pariatur voluptas blanditiis, sit voluptatem, explicabo officia distinctio culpa numquam.",
        price: 200,
        photo: "https://yandex-images.clstorage.net/v5v2IP199/5528ad7KU3/EDW0krcB9x4OBwQB0jn9pwcHb5ZFWnnx5tClAMDkos5wLszxhgGAeKy5TW0_ULVjuWMcoIoR3MkmwgMHDPu6ZFNtod7yRexGXEUYVdo6-KUaWiyHWQB9rPyS-Q_R66nDdi-O8dwQ2X7i8Ec4VDvDEM0NMsCgMK3iMtBBERCi5DIDLO6RvC2GUzoCYw7qNdeDDl5WiXMXY6rC8skE8KCRswlJ2Pr1Gq9h1dEWY08P-jXYCDHWhgWTyTfeVVw8qMQdDiGsqYk1ugEkJmse8T_AoBloUIFWFkaY2OHbKMubj6smb9La3TqmaNDRFmZZPu0c2TkV3IU8ruYEzVxUKrvYJi8sqoKtBKM9JidLKfEC_ocNXXCgQhxjp_7N3SHbkqqGCnXR5dkhukHw4yBkaQvJPNomMOieG7bCHOhcSjqP2RE1EYeBpzuOADodeTbwMcC1B25EgnYNUqPc4P447KiArihM7N_VDrhW1NcCbUwI9yDVJS34ugeryiLlXlMklfwsFyCkvqs-nhsCGGYy9DHLlSlrQppLEmmqyvvrKtmeqosXaMrR3guYQ93FEkRZL8wS4wQ41YI5t-kE7WduCILjDiURsbyNCIEeLSFgLNcS6o0sU2inSztZpevc9ib2hYuuP3Xw3dQxlWnz6jhZQCPlJ808MvqPGpXpI_JOTzmV7y8CMpqiih2wMAMNTS_wB-qRMmRQvlwzcbfm8-wm-6eJjC56x8rgFJh31sg-a008-xnXMBThjxuTyQP-YlMLrcsTCheoho0VnR0lPE0r3i7btAdbTbl6EHaa9_LvCPuKqbsvTfnd6wabee_rHEhCEuMg9QY5yKAOkN0Ew0ZaIILiOAsyraaNCLoQOBx-CPc80LEYSFKrQCdCotjzwCjEiY-dI13ZysIniXns8DJ4eCXpP84cKce-DbbrE_dydA6oxycrGqmGqRadNzADfjzCPcGmDF17pmE2dprL5tYLxIM"
    },
    {
        id: 3,
        name: "Third item",
        description: "Mock description for item number three. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Veritatis fugit maiores saepe aliquid nostrum libero aut, debitis reprehenderit, mollitia quo recusandae deleniti a omnis dolore quibusdam exercitationem, doloribus temporibus minima excepturi! Distinctio, placeat quis vel reprehenderit repellendus ipsum dicta officiis quaerat voluptatibus qui repellat molestias nihil, officia, dignissimos minus facilis! Excepturi perspiciatis distinctio quos aut doloremque, similique veniam explicabo porro illum illo velit repudiandae beatae eveniet qui labore deserunt placeat dolor repellendus repellat nostrum at! Modi eligendi nesciunt blanditiis soluta mollitia deserunt veritatis placeat. Illo, voluptas sit? Doloribus nisi odio pariatur voluptas blanditiis, sit voluptatem, explicabo officia distinctio culpa numquam.",
        price: 500,
        photo: "https://yandex-images.clstorage.net/v5v2IP199/5528ad7KU3/EDW0krcB9x4OBwQB0jn9pwcHb5ZFWnnx5tClAMDkos5wLszxhgGAeKy5TW0_ULVjuWMcoIoR3MkmwgMHDPu6ZFNtod7yRexGXEUYVdo6-KUaWiyHWQB9rPyS-Q_R66nDdi-O8dwQ2X7i8Ec4VDvDEM0NMsCgMK3iMtBBERCi5DIDLO6RvC2GUzoCYw7qNdeDDl5WiXMXY6rC8skE8KCRswlJ2Pr1Gq9h1dEWY08P-jXYCDHWhgWTyTfeVVw8qMQdDiGsqYk1ugEkJmse8T_AoBloUIFWFkaY2OHbKMubj6smb9La3TqmaNDRFmZZPu0c2TkV3IU8ruYEzVxUKrvYJi8sqoKtBKM9JidLKfEC_ocNXXCgQhxjp_7N3SHbkqqGCnXR5dkhukHw4yBkaQvJPNomMOieG7bCHOhcSjqP2RE1EYeBpzuOADodeTbwMcC1B25EgnYNUqPc4P447KiArihM7N_VDrhW1NcCbUwI9yDVJS34ugeryiLlXlMklfwsFyCkvqs-nhsCGGYy9DHLlSlrQppLEmmqyvvrKtmeqosXaMrR3guYQ93FEkRZL8wS4wQ41YI5t-kE7WduCILjDiURsbyNCIEeLSFgLNcS6o0sU2inSztZpevc9ib2hYuuP3Xw3dQxlWnz6jhZQCPlJ808MvqPGpXpI_JOTzmV7y8CMpqiih2wMAMNTS_wB-qRMmRQvlwzcbfm8-wm-6eJjC56x8rgFJh31sg-a008-xnXMBThjxuTyQP-YlMLrcsTCheoho0VnR0lPE0r3i7btAdbTbl6EHaa9_LvCPuKqbsvTfnd6wabee_rHEhCEuMg9QY5yKAOkN0Ew0ZaIILiOAsyraaNCLoQOBx-CPc80LEYSFKrQCdCotjzwCjEiY-dI13ZysIniXns8DJ4eCXpP84cKce-DbbrE_dydA6oxycrGqmGqRadNzADfjzCPcGmDF17pmE2dprL5tYLxIM"
    },
    {
        id: 4,
        name: "Fourth item",
        description: "Mock description for item number four. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Veritatis fugit maiores saepe aliquid nostrum libero aut, debitis reprehenderit, mollitia quo recusandae deleniti a omnis dolore quibusdam exercitationem, doloribus temporibus minima excepturi! Distinctio, placeat quis vel reprehenderit repellendus ipsum dicta officiis quaerat voluptatibus qui repellat molestias nihil, officia, dignissimos minus facilis! Excepturi perspiciatis distinctio quos aut doloremque, similique veniam explicabo porro illum illo velit repudiandae beatae eveniet qui labore deserunt placeat dolor repellendus repellat nostrum at! Modi eligendi nesciunt blanditiis soluta mollitia deserunt veritatis placeat. Illo, voluptas sit? Doloribus nisi odio pariatur voluptas blanditiis, sit voluptatem, explicabo officia distinctio culpa numquam.",
        price: 400,
        photo: "https://yandex-images.clstorage.net/v5v2IP199/5528ad7KU3/EDW0krcB9x4OBwQB0jn9pwcHb5ZFWnnx5tClAMDkos5wLszxhgGAeKy5TW0_ULVjuWMcoIoR3MkmwgMHDPu6ZFNtod7yRexGXEUYVdo6-KUaWiyHWQB9rPyS-Q_R66nDdi-O8dwQ2X7i8Ec4VDvDEM0NMsCgMK3iMtBBERCi5DIDLO6RvC2GUzoCYw7qNdeDDl5WiXMXY6rC8skE8KCRswlJ2Pr1Gq9h1dEWY08P-jXYCDHWhgWTyTfeVVw8qMQdDiGsqYk1ugEkJmse8T_AoBloUIFWFkaY2OHbKMubj6smb9La3TqmaNDRFmZZPu0c2TkV3IU8ruYEzVxUKrvYJi8sqoKtBKM9JidLKfEC_ocNXXCgQhxjp_7N3SHbkqqGCnXR5dkhukHw4yBkaQvJPNomMOieG7bCHOhcSjqP2RE1EYeBpzuOADodeTbwMcC1B25EgnYNUqPc4P447KiArihM7N_VDrhW1NcCbUwI9yDVJS34ugeryiLlXlMklfwsFyCkvqs-nhsCGGYy9DHLlSlrQppLEmmqyvvrKtmeqosXaMrR3guYQ93FEkRZL8wS4wQ41YI5t-kE7WduCILjDiURsbyNCIEeLSFgLNcS6o0sU2inSztZpevc9ib2hYuuP3Xw3dQxlWnz6jhZQCPlJ808MvqPGpXpI_JOTzmV7y8CMpqiih2wMAMNTS_wB-qRMmRQvlwzcbfm8-wm-6eJjC56x8rgFJh31sg-a008-xnXMBThjxuTyQP-YlMLrcsTCheoho0VnR0lPE0r3i7btAdbTbl6EHaa9_LvCPuKqbsvTfnd6wabee_rHEhCEuMg9QY5yKAOkN0Ew0ZaIILiOAsyraaNCLoQOBx-CPc80LEYSFKrQCdCotjzwCjEiY-dI13ZysIniXns8DJ4eCXpP84cKce-DbbrE_dydA6oxycrGqmGqRadNzADfjzCPcGmDF17pmE2dprL5tYLxIM"
    },
    {
        id: 5,
        name: "Fith item",
        description: "Mock description for item number five. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Veritatis fugit maiores saepe aliquid nostrum libero aut, debitis reprehenderit, mollitia quo recusandae deleniti a omnis dolore quibusdam exercitationem, doloribus temporibus minima excepturi! Distinctio, placeat quis vel reprehenderit repellendus ipsum dicta officiis quaerat voluptatibus qui repellat molestias nihil, officia, dignissimos minus facilis! Excepturi perspiciatis distinctio quos aut doloremque, similique veniam explicabo porro illum illo velit repudiandae beatae eveniet qui labore deserunt placeat dolor repellendus repellat nostrum at! Modi eligendi nesciunt blanditiis soluta mollitia deserunt veritatis placeat. Illo, voluptas sit? Doloribus nisi odio pariatur voluptas blanditiis, sit voluptatem, explicabo officia distinctio culpa numquam.",
        price: 600,
        photo: "https://yandex-images.clstorage.net/v5v2IP199/5528ad7KU3/EDW0krcB9x4OBwQB0jn9pwcHb5ZFWnnx5tClAMDkos5wLszxhgGAeKy5TW0_ULVjuWMcoIoR3MkmwgMHDPu6ZFNtod7yRexGXEUYVdo6-KUaWiyHWQB9rPyS-Q_R66nDdi-O8dwQ2X7i8Ec4VDvDEM0NMsCgMK3iMtBBERCi5DIDLO6RvC2GUzoCYw7qNdeDDl5WiXMXY6rC8skE8KCRswlJ2Pr1Gq9h1dEWY08P-jXYCDHWhgWTyTfeVVw8qMQdDiGsqYk1ugEkJmse8T_AoBloUIFWFkaY2OHbKMubj6smb9La3TqmaNDRFmZZPu0c2TkV3IU8ruYEzVxUKrvYJi8sqoKtBKM9JidLKfEC_ocNXXCgQhxjp_7N3SHbkqqGCnXR5dkhukHw4yBkaQvJPNomMOieG7bCHOhcSjqP2RE1EYeBpzuOADodeTbwMcC1B25EgnYNUqPc4P447KiArihM7N_VDrhW1NcCbUwI9yDVJS34ugeryiLlXlMklfwsFyCkvqs-nhsCGGYy9DHLlSlrQppLEmmqyvvrKtmeqosXaMrR3guYQ93FEkRZL8wS4wQ41YI5t-kE7WduCILjDiURsbyNCIEeLSFgLNcS6o0sU2inSztZpevc9ib2hYuuP3Xw3dQxlWnz6jhZQCPlJ808MvqPGpXpI_JOTzmV7y8CMpqiih2wMAMNTS_wB-qRMmRQvlwzcbfm8-wm-6eJjC56x8rgFJh31sg-a008-xnXMBThjxuTyQP-YlMLrcsTCheoho0VnR0lPE0r3i7btAdbTbl6EHaa9_LvCPuKqbsvTfnd6wabee_rHEhCEuMg9QY5yKAOkN0Ew0ZaIILiOAsyraaNCLoQOBx-CPc80LEYSFKrQCdCotjzwCjEiY-dI13ZysIniXns8DJ4eCXpP84cKce-DbbrE_dydA6oxycrGqmGqRadNzADfjzCPcGmDF17pmE2dprL5tYLxIM"
    },
    {
        id: 6,
        name: "Sixth item",
        description: "Mock description for item number six. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Veritatis fugit maiores saepe aliquid nostrum libero aut, debitis reprehenderit, mollitia quo recusandae deleniti a omnis dolore quibusdam exercitationem, doloribus temporibus minima excepturi! Distinctio, placeat quis vel reprehenderit repellendus ipsum dicta officiis quaerat voluptatibus qui repellat molestias nihil, officia, dignissimos minus facilis! Excepturi perspiciatis distinctio quos aut doloremque, similique veniam explicabo porro illum illo velit repudiandae beatae eveniet qui labore deserunt placeat dolor repellendus repellat nostrum at! Modi eligendi nesciunt blanditiis soluta mollitia deserunt veritatis placeat. Illo, voluptas sit? Doloribus nisi odio pariatur voluptas blanditiis, sit voluptatem, explicabo officia distinctio culpa numquam.",
        price: 800,
        photo: "https://yandex-images.clstorage.net/v5v2IP199/5528ad7KU3/EDW0krcB9x4OBwQB0jn9pwcHb5ZFWnnx5tClAMDkos5wLszxhgGAeKy5TW0_ULVjuWMcoIoR3MkmwgMHDPu6ZFNtod7yRexGXEUYVdo6-KUaWiyHWQB9rPyS-Q_R66nDdi-O8dwQ2X7i8Ec4VDvDEM0NMsCgMK3iMtBBERCi5DIDLO6RvC2GUzoCYw7qNdeDDl5WiXMXY6rC8skE8KCRswlJ2Pr1Gq9h1dEWY08P-jXYCDHWhgWTyTfeVVw8qMQdDiGsqYk1ugEkJmse8T_AoBloUIFWFkaY2OHbKMubj6smb9La3TqmaNDRFmZZPu0c2TkV3IU8ruYEzVxUKrvYJi8sqoKtBKM9JidLKfEC_ocNXXCgQhxjp_7N3SHbkqqGCnXR5dkhukHw4yBkaQvJPNomMOieG7bCHOhcSjqP2RE1EYeBpzuOADodeTbwMcC1B25EgnYNUqPc4P447KiArihM7N_VDrhW1NcCbUwI9yDVJS34ugeryiLlXlMklfwsFyCkvqs-nhsCGGYy9DHLlSlrQppLEmmqyvvrKtmeqosXaMrR3guYQ93FEkRZL8wS4wQ41YI5t-kE7WduCILjDiURsbyNCIEeLSFgLNcS6o0sU2inSztZpevc9ib2hYuuP3Xw3dQxlWnz6jhZQCPlJ808MvqPGpXpI_JOTzmV7y8CMpqiih2wMAMNTS_wB-qRMmRQvlwzcbfm8-wm-6eJjC56x8rgFJh31sg-a008-xnXMBThjxuTyQP-YlMLrcsTCheoho0VnR0lPE0r3i7btAdbTbl6EHaa9_LvCPuKqbsvTfnd6wabee_rHEhCEuMg9QY5yKAOkN0Ew0ZaIILiOAsyraaNCLoQOBx-CPc80LEYSFKrQCdCotjzwCjEiY-dI13ZysIniXns8DJ4eCXpP84cKce-DbbrE_dydA6oxycrGqmGqRadNzADfjzCPcGmDF17pmE2dprL5tYLxIM"
    },
    {
        id: 7,
        name: "Seventh item",
        description: "Mock description for item number seven. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Veritatis fugit maiores saepe aliquid nostrum libero aut, debitis reprehenderit, mollitia quo recusandae deleniti a omnis dolore quibusdam exercitationem, doloribus temporibus minima excepturi! Distinctio, placeat quis vel reprehenderit repellendus ipsum dicta officiis quaerat voluptatibus qui repellat molestias nihil, officia, dignissimos minus facilis! Excepturi perspiciatis distinctio quos aut doloremque, similique veniam explicabo porro illum illo velit repudiandae beatae eveniet qui labore deserunt placeat dolor repellendus repellat nostrum at! Modi eligendi nesciunt blanditiis soluta mollitia deserunt veritatis placeat. Illo, voluptas sit? Doloribus nisi odio pariatur voluptas blanditiis, sit voluptatem, explicabo officia distinctio culpa numquam.",
        price: 900,
        photo: "https://yandex-images.clstorage.net/v5v2IP199/5528ad7KU3/EDW0krcB9x4OBwQB0jn9pwcHb5ZFWnnx5tClAMDkos5wLszxhgGAeKy5TW0_ULVjuWMcoIoR3MkmwgMHDPu6ZFNtod7yRexGXEUYVdo6-KUaWiyHWQB9rPyS-Q_R66nDdi-O8dwQ2X7i8Ec4VDvDEM0NMsCgMK3iMtBBERCi5DIDLO6RvC2GUzoCYw7qNdeDDl5WiXMXY6rC8skE8KCRswlJ2Pr1Gq9h1dEWY08P-jXYCDHWhgWTyTfeVVw8qMQdDiGsqYk1ugEkJmse8T_AoBloUIFWFkaY2OHbKMubj6smb9La3TqmaNDRFmZZPu0c2TkV3IU8ruYEzVxUKrvYJi8sqoKtBKM9JidLKfEC_ocNXXCgQhxjp_7N3SHbkqqGCnXR5dkhukHw4yBkaQvJPNomMOieG7bCHOhcSjqP2RE1EYeBpzuOADodeTbwMcC1B25EgnYNUqPc4P447KiArihM7N_VDrhW1NcCbUwI9yDVJS34ugeryiLlXlMklfwsFyCkvqs-nhsCGGYy9DHLlSlrQppLEmmqyvvrKtmeqosXaMrR3guYQ93FEkRZL8wS4wQ41YI5t-kE7WduCILjDiURsbyNCIEeLSFgLNcS6o0sU2inSztZpevc9ib2hYuuP3Xw3dQxlWnz6jhZQCPlJ808MvqPGpXpI_JOTzmV7y8CMpqiih2wMAMNTS_wB-qRMmRQvlwzcbfm8-wm-6eJjC56x8rgFJh31sg-a008-xnXMBThjxuTyQP-YlMLrcsTCheoho0VnR0lPE0r3i7btAdbTbl6EHaa9_LvCPuKqbsvTfnd6wabee_rHEhCEuMg9QY5yKAOkN0Ew0ZaIILiOAsyraaNCLoQOBx-CPc80LEYSFKrQCdCotjzwCjEiY-dI13ZysIniXns8DJ4eCXpP84cKce-DbbrE_dydA6oxycrGqmGqRadNzADfjzCPcGmDF17pmE2dprL5tYLxIM"
    }
]