import { UserProduct } from "./interfaces/user-product";

export const USER_PRODUCT: UserProduct[] = [
    { id: 1, user_id: 2, product_id: 4 },
    { id: 2, user_id: 1, product_id: 5 },
    { id: 3, user_id: 2, product_id: 1 },
    { id: 4, user_id: 1, product_id: 6 },
    { id: 5, user_id: 3, product_id: 7 },
    { id: 6, user_id: 2, product_id: 3 },
    { id: 7, user_id: 3, product_id: 2 },
    { id: 8, user_id: 1, product_id: 7 },
    { id: 9, user_id: 2, product_id: 6 },
    { id: 10, user_id: 3, product_id: 1 },
    { id: 11, user_id: 1, product_id: 2 },
    { id: 12, user_id: 2, product_id: 7 },
    { id: 13, user_id: 3, product_id: 4 },
    { id: 14, user_id: 1, product_id: 3 },
    { id: 15, user_id: 2, product_id: 2 },
    { id: 16, user_id: 1, product_id: 1 },
    { id: 17, user_id: 3, product_id: 6 },
    { id: 18, user_id: 1, product_id: 4 },
    { id: 19, user_id: 3, product_id: 3 },
    { id: 20, user_id: 2, product_id: 5 },
    { id: 21, user_id: 1, product_id: 2 },
    { id: 22, user_id: 3, product_id: 1 },
    { id: 23, user_id: 2, product_id: 7 },
    { id: 24, user_id: 1, product_id: 6 },
    { id: 25, user_id: 3, product_id: 5 },
];